"""Add original_predecessor field to Item model

Revision ID: 150f10597160
Revises: 
Create Date: 2024-11-02 16:48:22.593049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150f10597160'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    op.drop_table('user_roles')
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               nullable=True)
        batch_op.drop_column('first_name')
        batch_op.drop_column('email_confirmed_at')
        batch_op.drop_column('last_name')
        batch_op.drop_column('active')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_predecessor', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_items_item_group_id'), ['item_group_id'], unique=False)

    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirements_code_name'), ['code_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_course_id'), ['course_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirements_course_id'))
        batch_op.drop_index(batch_op.f('ix_requirements_code_name'))

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_item_group_id'))
        batch_op.drop_column('original_predecessor')

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=50), server_default=sa.text("('')"), nullable=False))
        batch_op.add_column(sa.Column('email_confirmed_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=50), server_default=sa.text("('')"), nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=False)

    op.create_table('user_roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
