"""Add original_predecessor field to Item model

Revision ID: 7d6ab5a35c96
Revises: 150f10597160
Create Date: 2024-11-02 16:50:42.460383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d6ab5a35c96'
down_revision = '150f10597160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_simultaneous', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('original_simultaneous')

    # ### end Alembic commands ###
